# Generated by Django 4.2.10 on 2024-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0003_course_course_type'),
        ('day2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='day4app.course'),
        ),
    ]
