# Generated by Django 5.0 on 2023-12-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
